"""bigint baseline

The single baseline migration after the primary-key type was changed from UUID to
a DB-generated bigint across every table. Supersedes the previous UUID-era chain,
which was removed wholesale because the database had never been created.

Revision ID: a21f5126d792
Revises:
Create Date: 2026-09-01 23:44:09.145481

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a21f5126d792"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_matrices',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=False),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_matrices_code'), 'approval_matrices', ['code'], unique=True)
    op.create_index(op.f('ix_approval_matrices_entity_type'), 'approval_matrices', ['entity_type'], unique=False)
    op.create_index(op.f('ix_approval_matrices_name'), 'approval_matrices', ['name'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('actor_username', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=False),
    sa.Column('extra_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_username'), 'audit_logs', ['actor_username'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_table('countries',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('iso3_code', sa.String(length=10), nullable=True),
    sa.Column('dial_code', sa.String(length=10), nullable=True),
    sa.Column('currency_code', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=False),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_countries_code'), 'countries', ['code'], unique=True)
    op.create_index(op.f('ix_countries_name'), 'countries', ['name'], unique=True)
    op.create_table('permissions',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('resource', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=False),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_index(op.f('ix_permissions_resource'), 'permissions', ['resource'], unique=False)
    op.create_index(op.f('ix_permissions_scope'), 'permissions', ['scope'], unique=False)
    op.create_table('task_types',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=False),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_types_code'), 'task_types', ['code'], unique=True)
    op.create_index(op.f('ix_task_types_name'), 'task_types', ['name'], unique=True)
    op.create_table('tenants',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=False),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_code'), 'tenants', ['code'], unique=True)
    op.create_index(op.f('ix_tenants_domain'), 'tenants', ['domain'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('is_validate_ad', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=False),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('workflow_definitions',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=False),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_definitions_code'), 'workflow_definitions', ['code'], unique=True)
    op.create_index(op.f('ix_workflow_definitions_entity_type'), 'workflow_definitions', ['entity_type'], unique=False)
    op.create_index(op.f('ix_workflow_definitions_name'), 'workflow_definitions', ['name'], unique=True)
    op.create_table('approval_rules',
    sa.Column('matrix_id', sa.BigInteger(), nullable=False),
    sa.Column('field', sa.String(length=100), nullable=False),
    sa.Column('operator', sa.String(length=20), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('data_type', sa.String(length=20), nullable=False),
    sa.Column('logical_group', sa.String(length=50), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=False),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['matrix_id'], ['approval_matrices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_rules_matrix_id'), 'approval_rules', ['matrix_id'], unique=False)
    op.create_table('roles',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=True),
    sa.Column('parent_role_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=False),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=True)
    op.create_index(op.f('ix_roles_tenant_id'), 'roles', ['tenant_id'], unique=False)
    op.create_table('states',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country_id', sa.BigInteger(), nullable=False),
    sa.Column('is_union_territory', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=False),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_id', 'name', name='uq_states_country_name')
    )
    op.create_index(op.f('ix_states_code'), 'states', ['code'], unique=True)
    op.create_index(op.f('ix_states_country_id'), 'states', ['country_id'], unique=False)
    op.create_index(op.f('ix_states_name'), 'states', ['name'], unique=False)
    op.create_table('user_details',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('employee_name', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('middle_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('designation_title', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('business_unit', sa.String(length=255), nullable=False),
    sa.Column('group_company', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=255), nullable=False),
    sa.Column('zone', sa.String(length=255), nullable=False),
    sa.Column('grade', sa.String(length=50), nullable=False),
    sa.Column('office_mobile_no', sa.String(length=50), nullable=False),
    sa.Column('personal_mobile_no', sa.String(length=50), nullable=False),
    sa.Column('date_of_joining', sa.String(length=50), nullable=False),
    sa.Column('reporting_manager', sa.String(length=255), nullable=False),
    sa.Column('direct_manager_employee_id', sa.String(length=50), nullable=False),
    sa.Column('direct_manager_name', sa.String(length=255), nullable=False),
    sa.Column('direct_manager_email', sa.String(length=255), nullable=False),
    sa.Column('sap_user_id', sa.String(length=50), nullable=False),
    sa.Column('division_id', sa.String(length=50), nullable=False),
    sa.Column('territory_id', sa.String(length=50), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=False),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_details_employee_id'), 'user_details', ['employee_id'], unique=False)
    op.create_table('workflow_statuses',
    sa.Column('workflow_definition_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_initial', sa.Boolean(), nullable=False),
    sa.Column('is_terminal', sa.Boolean(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=False),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workflow_definition_id'], ['workflow_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_definition_id', 'code', name='uq_workflow_statuses_definition_code')
    )
    op.create_index(op.f('ix_workflow_statuses_code'), 'workflow_statuses', ['code'], unique=False)
    op.create_index(op.f('ix_workflow_statuses_workflow_definition_id'), 'workflow_statuses', ['workflow_definition_id'], unique=False)
    op.create_table('approval_assignments',
    sa.Column('matrix_id', sa.BigInteger(), nullable=False),
    sa.Column('assignment_type', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('role_id', sa.BigInteger(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=False),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['matrix_id'], ['approval_matrices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_assignments_matrix_id'), 'approval_assignments', ['matrix_id'], unique=False)
    op.create_index(op.f('ix_approval_assignments_role_id'), 'approval_assignments', ['role_id'], unique=False)
    op.create_index(op.f('ix_approval_assignments_user_id'), 'approval_assignments', ['user_id'], unique=False)
    op.create_table('categories_of_law',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('state_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=False),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state_id', 'name', name='uq_categories_of_law_state_name')
    )
    op.create_index(op.f('ix_categories_of_law_code'), 'categories_of_law', ['code'], unique=True)
    op.create_index(op.f('ix_categories_of_law_name'), 'categories_of_law', ['name'], unique=False)
    op.create_index(op.f('ix_categories_of_law_state_id'), 'categories_of_law', ['state_id'], unique=False)
    op.create_table('role_assignments',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=False),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_assignments_role_id'), 'role_assignments', ['role_id'], unique=False)
    op.create_index(op.f('ix_role_assignments_tenant_id'), 'role_assignments', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_role_assignments_user_id'), 'role_assignments', ['user_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('permission_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=False),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_table('workflow_instances',
    sa.Column('workflow_definition_id', sa.BigInteger(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('current_status_id', sa.BigInteger(), nullable=False),
    sa.Column('initiated_by', sa.BigInteger(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),  # type: ignore[no-untyped-call]
    sa.Column('approval_level', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=False),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['current_status_id'], ['workflow_statuses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['initiated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workflow_definition_id'], ['workflow_definitions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_instances_completed_at'), 'workflow_instances', ['completed_at'], unique=False)
    op.create_index(op.f('ix_workflow_instances_current_status_id'), 'workflow_instances', ['current_status_id'], unique=False)
    op.create_index('ix_workflow_instances_entity', 'workflow_instances', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_workflow_instances_entity_id'), 'workflow_instances', ['entity_id'], unique=False)
    op.create_index(op.f('ix_workflow_instances_entity_type'), 'workflow_instances', ['entity_type'], unique=False)
    op.create_index(op.f('ix_workflow_instances_initiated_by'), 'workflow_instances', ['initiated_by'], unique=False)
    op.create_index(op.f('ix_workflow_instances_workflow_definition_id'), 'workflow_instances', ['workflow_definition_id'], unique=False)
    op.create_table('workflow_transitions',
    sa.Column('workflow_definition_id', sa.BigInteger(), nullable=False),
    sa.Column('from_status_id', sa.BigInteger(), nullable=False),
    sa.Column('to_status_id', sa.BigInteger(), nullable=False),
    sa.Column('action_code', sa.String(length=50), nullable=False),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('guard_expression', sa.Text(), nullable=True),
    sa.Column('requires_comment', sa.Boolean(), nullable=False),
    sa.Column('auto_execute', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=False),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_status_id'], ['workflow_statuses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_status_id'], ['workflow_statuses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_definition_id'], ['workflow_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_definition_id', 'from_status_id', 'action_code', name='uq_workflow_transitions_from_action')
    )
    op.create_index(op.f('ix_workflow_transitions_action_code'), 'workflow_transitions', ['action_code'], unique=False)
    op.create_index(op.f('ix_workflow_transitions_from_status_id'), 'workflow_transitions', ['from_status_id'], unique=False)
    op.create_index(op.f('ix_workflow_transitions_to_status_id'), 'workflow_transitions', ['to_status_id'], unique=False)
    op.create_index(op.f('ix_workflow_transitions_workflow_definition_id'), 'workflow_transitions', ['workflow_definition_id'], unique=False)
    op.create_table('approval_tasks',
    sa.Column('instance_id', sa.BigInteger(), nullable=False),
    sa.Column('matrix_id', sa.BigInteger(), nullable=True),
    sa.Column('assignee_id', sa.BigInteger(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('action_taken', sa.String(length=50), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=False),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matrix_id'], ['approval_matrices.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instance_id', 'assignee_id', 'level', name='uq_approval_tasks_instance_assignee_level')
    )
    op.create_index(op.f('ix_approval_tasks_assignee_id'), 'approval_tasks', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_approval_tasks_due_date'), 'approval_tasks', ['due_date'], unique=False)
    op.create_index(op.f('ix_approval_tasks_instance_id'), 'approval_tasks', ['instance_id'], unique=False)
    op.create_index(op.f('ix_approval_tasks_matrix_id'), 'approval_tasks', ['matrix_id'], unique=False)
    op.create_index(op.f('ix_approval_tasks_status'), 'approval_tasks', ['status'], unique=False)
    op.create_table('legislations',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category_of_law_id', sa.BigInteger(), nullable=False),
    sa.Column('state_id', sa.BigInteger(), nullable=True),
    sa.Column('country_id', sa.BigInteger(), nullable=False),
    sa.Column('legislation_number', sa.String(length=100), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=False),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_of_law_id'], ['categories_of_law.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legislations_category_of_law_id'), 'legislations', ['category_of_law_id'], unique=False)
    op.create_index(op.f('ix_legislations_code'), 'legislations', ['code'], unique=True)
    op.create_index(op.f('ix_legislations_country_id'), 'legislations', ['country_id'], unique=False)
    op.create_index(op.f('ix_legislations_name'), 'legislations', ['name'], unique=False)
    op.create_index(op.f('ix_legislations_state_id'), 'legislations', ['state_id'], unique=False)
    op.create_table('workflow_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('instance_id', sa.BigInteger(), nullable=False),
    sa.Column('from_status_id', sa.BigInteger(), nullable=True),
    sa.Column('to_status_id', sa.BigInteger(), nullable=False),
    sa.Column('action_code', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('actor_username', sa.String(length=255), nullable=False),
    sa.Column('comments', sa.Text(), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),  # type: ignore[no-untyped-call]
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_history_action_code'), 'workflow_history', ['action_code'], unique=False)
    op.create_index(op.f('ix_workflow_history_created_at'), 'workflow_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_workflow_history_instance_id'), 'workflow_history', ['instance_id'], unique=False)
    op.create_table('rules',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('legislation_id', sa.BigInteger(), nullable=False),
    sa.Column('state_id', sa.BigInteger(), nullable=True),
    sa.Column('country_id', sa.BigInteger(), nullable=False),
    sa.Column('rule_number', sa.String(length=100), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=False),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['legislation_id'], ['legislations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rules_code'), 'rules', ['code'], unique=True)
    op.create_index(op.f('ix_rules_country_id'), 'rules', ['country_id'], unique=False)
    op.create_index(op.f('ix_rules_legislation_id'), 'rules', ['legislation_id'], unique=False)
    op.create_index(op.f('ix_rules_name'), 'rules', ['name'], unique=False)
    op.create_index(op.f('ix_rules_state_id'), 'rules', ['state_id'], unique=False)
    # ### end Alembic commands ###

    # Seed the three system roles. Ids are DB-assigned (bigint identity), so no
    # explicit id is given — this replaces the old gen_random_uuid() seed.
    op.execute(
        """
        INSERT INTO roles
            (code, name, description, is_system, is_active,
             created_by, modified_by, created_date, modified_date)
        VALUES
            ('ADMIN', 'Administrator', 'Full system access', true, true,
             'migration', 'migration', NOW(), NOW()),
            ('MANAGER', 'Manager', 'Department management access', true, true,
             'migration', 'migration', NOW(), NOW()),
            ('USER', 'Standard User', 'Basic application access', true, true,
             'migration', 'migration', NOW(), NOW())
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rules_state_id'), table_name='rules')
    op.drop_index(op.f('ix_rules_name'), table_name='rules')
    op.drop_index(op.f('ix_rules_legislation_id'), table_name='rules')
    op.drop_index(op.f('ix_rules_country_id'), table_name='rules')
    op.drop_index(op.f('ix_rules_code'), table_name='rules')
    op.drop_table('rules')
    op.drop_index(op.f('ix_workflow_history_instance_id'), table_name='workflow_history')
    op.drop_index(op.f('ix_workflow_history_created_at'), table_name='workflow_history')
    op.drop_index(op.f('ix_workflow_history_action_code'), table_name='workflow_history')
    op.drop_table('workflow_history')
    op.drop_index(op.f('ix_legislations_state_id'), table_name='legislations')
    op.drop_index(op.f('ix_legislations_name'), table_name='legislations')
    op.drop_index(op.f('ix_legislations_country_id'), table_name='legislations')
    op.drop_index(op.f('ix_legislations_code'), table_name='legislations')
    op.drop_index(op.f('ix_legislations_category_of_law_id'), table_name='legislations')
    op.drop_table('legislations')
    op.drop_index(op.f('ix_approval_tasks_status'), table_name='approval_tasks')
    op.drop_index(op.f('ix_approval_tasks_matrix_id'), table_name='approval_tasks')
    op.drop_index(op.f('ix_approval_tasks_instance_id'), table_name='approval_tasks')
    op.drop_index(op.f('ix_approval_tasks_due_date'), table_name='approval_tasks')
    op.drop_index(op.f('ix_approval_tasks_assignee_id'), table_name='approval_tasks')
    op.drop_table('approval_tasks')
    op.drop_index(op.f('ix_workflow_transitions_workflow_definition_id'), table_name='workflow_transitions')
    op.drop_index(op.f('ix_workflow_transitions_to_status_id'), table_name='workflow_transitions')
    op.drop_index(op.f('ix_workflow_transitions_from_status_id'), table_name='workflow_transitions')
    op.drop_index(op.f('ix_workflow_transitions_action_code'), table_name='workflow_transitions')
    op.drop_table('workflow_transitions')
    op.drop_index(op.f('ix_workflow_instances_workflow_definition_id'), table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_initiated_by'), table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_entity_type'), table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_entity_id'), table_name='workflow_instances')
    op.drop_index('ix_workflow_instances_entity', table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_current_status_id'), table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_completed_at'), table_name='workflow_instances')
    op.drop_table('workflow_instances')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_role_assignments_user_id'), table_name='role_assignments')
    op.drop_index(op.f('ix_role_assignments_tenant_id'), table_name='role_assignments')
    op.drop_index(op.f('ix_role_assignments_role_id'), table_name='role_assignments')
    op.drop_table('role_assignments')
    op.drop_index(op.f('ix_categories_of_law_state_id'), table_name='categories_of_law')
    op.drop_index(op.f('ix_categories_of_law_name'), table_name='categories_of_law')
    op.drop_index(op.f('ix_categories_of_law_code'), table_name='categories_of_law')
    op.drop_table('categories_of_law')
    op.drop_index(op.f('ix_approval_assignments_user_id'), table_name='approval_assignments')
    op.drop_index(op.f('ix_approval_assignments_role_id'), table_name='approval_assignments')
    op.drop_index(op.f('ix_approval_assignments_matrix_id'), table_name='approval_assignments')
    op.drop_table('approval_assignments')
    op.drop_index(op.f('ix_workflow_statuses_workflow_definition_id'), table_name='workflow_statuses')
    op.drop_index(op.f('ix_workflow_statuses_code'), table_name='workflow_statuses')
    op.drop_table('workflow_statuses')
    op.drop_index(op.f('ix_user_details_employee_id'), table_name='user_details')
    op.drop_table('user_details')
    op.drop_index(op.f('ix_states_name'), table_name='states')
    op.drop_index(op.f('ix_states_country_id'), table_name='states')
    op.drop_index(op.f('ix_states_code'), table_name='states')
    op.drop_table('states')
    op.drop_index(op.f('ix_roles_tenant_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_approval_rules_matrix_id'), table_name='approval_rules')
    op.drop_table('approval_rules')
    op.drop_index(op.f('ix_workflow_definitions_name'), table_name='workflow_definitions')
    op.drop_index(op.f('ix_workflow_definitions_entity_type'), table_name='workflow_definitions')
    op.drop_index(op.f('ix_workflow_definitions_code'), table_name='workflow_definitions')
    op.drop_table('workflow_definitions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tenants_domain'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_code'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_task_types_name'), table_name='task_types')
    op.drop_index(op.f('ix_task_types_code'), table_name='task_types')
    op.drop_table('task_types')
    op.drop_index(op.f('ix_permissions_scope'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_resource'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_countries_name'), table_name='countries')
    op.drop_index(op.f('ix_countries_code'), table_name='countries')
    op.drop_table('countries')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_username'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_approval_matrices_name'), table_name='approval_matrices')
    op.drop_index(op.f('ix_approval_matrices_entity_type'), table_name='approval_matrices')
    op.drop_index(op.f('ix_approval_matrices_code'), table_name='approval_matrices')
    op.drop_table('approval_matrices')
    # ### end Alembic commands ###
